import "./css/globals.css";
import "./css/app.css";

export const metadata = {
  title: "Anas Arbasha",
  description: "Generated by create next app",
  icons: {
    icon: "../../public/images/PngItem_3109938.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`custom-scrollbar`}>
        <div className="body">
          {children}
          <div className="Wave-1 wave"></div>
          <div className="Wave-2 wave"></div>
          <div className="Wave-3 wave"></div>
        </div>
      </body>
    </html>
  );
}
